{"uuid": "6f75f272-e6be-4965-b84e-48655f375d12", "children": ["5a1ea01b-be42-45ba-ab51-27d47de01fb9", "36fe0053-7797-4a23-b112-fed2bab1e749", "2b040ba9-ae09-44ea-932e-3c781af483ae", "8496c1b2-e307-4a1a-943d-482a328c2f58", "04e487e3-03cd-4a58-8814-31465a1758c1", "49be2ae6-3864-465d-9c84-655e0deb5b98", "5636ddec-56be-4117-9671-ca30af629131", "46265673-1d87-4cbe-94d2-6fb1622671d0", "358b7cc8-adca-4149-981a-1f1676af25cc", "06cbe58b-c19a-4abf-97a7-16b32601f504"], "befores": [{"name": "initWebDriver", "status": "broken", "statusDetails": {"message": "Exception: Wrong input, unrecognized browser!\n", "trace": "  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\serge\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\AtidAutomation\\FinalProjectInfrastructure\\WebMobile\\TestCases\\conftest.py\", line 68, in initWebDriver\n    edriver = GetWebDriver()\n  File \"D:\\AtidAutomation\\FinalProjectInfrastructure\\WebMobile\\TestCases\\conftest.py\", line 100, in GetWebDriver\n    raise Exception(\"Wrong input, unrecognized browser!\")\n"}, "start": 1665992895893, "stop": 1665992895894}], "start": 1665992895893, "stop": 1665992896235}